server:
  port: 8081
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:iam;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  secret: 12345